def nodetest() {
	echo ('alive on $(hostname)')
}
pipeline {
   agent { label 'MVP'}
    tools {
        maven 'Maven 3.6.0'
    }
parameters {
        booleanParam(
            name: 'Checkout',
            defaultValue: true,
        )
        booleanParam(
            name: 'Sonar',
            defaultValue: true,
        )
    }
stages {
 stage ('Checkout') {
	agent any
     when {
	 expression { params.Checkout == true }
	 }
           
           steps {
             build 'mod_checkout'
                 }
    }
 stage ('Sonarqube Code Analysis') {
	agent any
     when {
	 expression { params.Sonar == true }
	 }
           
           steps {
                build 'mod_sonarqube'
                 }
    }
    }
}
